apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: mock-rtp-creditor-acknowledgement
  labels:
    strimzi.io/cluster: rtp-demo-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
